# Site settings
title: *folio
email: emma.irwin@gmail.com
description: Remembering Patrick Irwin
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/
